language: php
php:
  - 7.2
  - 7.3
  - 7.4
dist: xenial
before_script:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files
after_success:
  - bash <(curl -s https://codecov.io/bash)